import { useEffect, useState } from 'react';
import axios from 'axios';
import { FileText, Download, Calendar, User, CheckCircle2, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import Navbar from '../components/Navbar';

function CarePlan() {
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();
  const user = JSON.parse(localStorage.getItem('user'));

  useEffect(() => {
    axios.get(`http://localhost:5000/api/my-plan/${user.id}`)
      .then(res => {
        setPlan(res.data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [user.id]);

  return (
    <div className="min-h-screen bg-slate-50">
      <Navbar />
      <div className="max-w-4xl mx-auto px-6 py-12">
        
        {/* Header Section */}
        <div className="flex items-center justify-between mb-8">
          <button onClick={() => navigate('/dashboard')} className="flex items-center gap-2 text-slate-500 hover:text-blue-600 transition-colors font-bold text-sm">
            <ArrowLeft size={18}/> Back to Dashboard
          </button>
          <button className="flex items-center gap-2 bg-white border border-slate-200 px-4 py-2 rounded-xl text-slate-600 font-bold text-sm hover:bg-slate-50 transition-all shadow-sm">
            <Download size={16}/> Download PDF
          </button>
        </div>

        {plan && plan.advice ? (
          <div className="bg-white rounded-[2.5rem] shadow-2xl shadow-slate-200 border border-slate-100 overflow-hidden">
            {/* Document Header */}
            <div className="bg-slate-900 p-10 text-white flex justify-between items-start">
              <div>
                <div className="flex items-center gap-2 mb-4">
                  <FileText className="text-blue-400" size={28} />
                  <h1 className="text-2xl font-black uppercase tracking-tighter">Medical Care Plan</h1>
                </div>
                <p className="text-slate-400 text-sm max-w-xs">Personalized health strategy generated by WellCare AI Specialists.</p>
              </div>
              <div className="text-right">
                <span className="bg-blue-600 px-3 py-1 rounded-md text-[10px] font-black tracking-widest uppercase">Verified</span>
                <p className="text-xs text-slate-400 mt-2 italic">Ref ID: {plan.id.split('-')[0]}</p>
              </div>
            </div>

            <div className="p-10 space-y-10">
              {/* Patient Info Row */}
              <div className="grid grid-cols-2 gap-8 border-b border-slate-100 pb-10">
                <div className="flex items-center gap-4">
                  <div className="bg-slate-100 p-3 rounded-2xl"><User className="text-slate-600" /></div>
                  <div>
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Patient Name</p>
                    <p className="font-bold text-slate-800 uppercase">{user.name}</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="bg-slate-100 p-3 rounded-2xl"><Calendar className="text-slate-600" /></div>
                  <div>
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Date Issued</p>
                    <p className="font-bold text-slate-800">{plan.date}</p>
                  </div>
                </div>
              </div>

              {/* Advice Content */}
              <div>
                <h3 className="text-lg font-black text-slate-800 mb-6 flex items-center gap-2">
                  <CheckCircle2 className="text-green-500" size={20} /> Specialist Recommendations
                </h3>
                <div className="bg-slate-50 p-8 rounded-3xl border border-slate-100 relative">
                   <div className="absolute top-0 right-0 p-4 opacity-10">
                      <FileText size={80} />
                   </div>
                   <p className="text-slate-700 leading-relaxed text-lg whitespace-pre-wrap relative z-10">
                    {plan.advice}
                   </p>
                </div>
              </div>

              {/* Footer Stamp */}
              <div className="pt-10 flex justify-between items-center border-t border-slate-100 mt-10">
                <div className="flex items-center gap-2">
                   <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white font-black text-[10px]">WC</div>
                   <p className="text-xs font-bold text-slate-400">WellCare AI Systems 2026</p>
                </div>
                <p className="text-xs text-slate-300 font-medium italic">Electronic signature verified.</p>
              </div>
            </div>
          </div>
        ) : (
          <div className="bg-white p-20 rounded-[3rem] text-center border-2 border-dashed border-slate-200">
            <div className="bg-slate-50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 text-slate-300">
              <FileText size={40} />
            </div>
            <h2 className="text-2xl font-bold text-slate-800 mb-2">No Plan Found</h2>
            <p className="text-slate-500 max-w-sm mx-auto">Your medical data is currently under specialist review. Please check back in a few hours.</p>
          </div>
        )}
      </div>
    </div>
  );
}

export default CarePlan;